# Generated by Django 3.1.2 on 2020-10-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=288)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=1000)),
                ('number_of_pages', models.IntegerField()),
            ],
        ),
    ]
